# Generated by Django 5.0.4 on 2024-05-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_course_code_alter_course_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
    ]
